export const challenges = [
  {
    topics: [`Sommeil`, `Productivité`, `Zen`],
    title: `Cocorico !`,
    subTitle: `Ne te lève pas après 06h00`,
    description: `Le cycle circadien de certaines personnes est optimisé pour récolter le soleil du matin. Ils vont être naturellement plus en forme en se levant tôt (en gardant bien sur une bonne durée de sommeil)`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Mets ton réveil à 6h00.`,
      `Ne pas appuyer sur ""snooze""`,
      `Quand ton réveil sonne, sors du lit dans les 30 secondes.`,
    ],
    coachAfterSummit: `Alors Alors cette matinée ? Pas mal ce qu’on peut faire quand l'on à du temps le matin ! :)`,
    notificationAfterCompletion: `Prêt pour découvrir tout ce qu’on peut faire le matin ? Ne te couche pas trop tard pour pleinement en profiter.`,
    notificationEvening: `C'est un excellent défi, le monde appartient a ceux qui se lèvent tôt :)`,
  },
  {
    topics: [`Sommeil`, `Santé`, ``],
    title: `8 bonnes heures`,
    subTitle: `Dors au moins 8 heures par nuit`,
    description: `Non, tu ne fais surement pas partie des exceptions qui ont seulement besoin de 4h de sommeil. Alors couche toi plus tôt et passe au moins 8h sur ton oreiller, tu me remercieras plus tard.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `La durée entre le moment où tu fermes les yeux pour t'endormir et l'heure de ton réveil doit être d'au moins 8h`,
      ``,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :8 bonnes heures`,
    notificationAfterCompletion: ``,
    notificationEvening: `Super, rallonge tes nuits, recharges toi, moi même je ... zzz...`,
  },
  {
    topics: [`Alimentation`, `Santé`, `Addiction`],
    title: `Une fois mais pas plus`,
    subTitle: `Ne consomme pas d'aliments trop sucrés plus d'une fois par jour`,
    description: `Les méfaits de l'excès de mauvais sucre ne sont plus à démontrer. Ta volonté à y résister, par contre, reste à démontrer.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Les interdits du jour sont : desserts, gâteaux, pâtisseries, bonbons, sodas, pâtes à tartiner, confitures`,
      `Notes chaque fois que tu as envie de craquer et compte un point mentalement`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Une fois mais pas plus`,
    notificationAfterCompletion: ``,
    notificationEvening: `Ouch, pas un facile celui la, mais pas le moins important, profite bien de ton ""cheap meal"".`,
  },
  {
    topics: [`Alimentation`, `Santé`, `Addiction`],
    title: `Une fois mais pas plus`,
    subTitle: `Ne consomme pas d'aliments trop sucrés plus d'une fois par jour`,
    description: `Les méfaits de l'excès de mauvais sucre ne sont plus à démontrer. Ta volonté à y résister, par contre, reste à démontrer.`,
    autoCompletion: false,
    duration: 3,
    level: 2,
    rules: [
      `Les interdits de la semaine sont : desserts, gâteaux, pâtisseries, bonbons, sodas, pâtes à tartiner, confitures`,
      `Un jour par semaine, tu peux consommer ce que tu veux. Ce jour peut varier de semaine en semaine, tu n'es pas obligé de le choisir à l'avance.`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Une fois mais pas plus`,
    notificationAfterCompletion: ``,
    notificationEvening: `Ouch, pas un facile celui la, mais pas le moins important, profite bien de ton ""cheap meal"".`,
  },
  {
    topics: [`Alimentation`, `Santé`, `Addiction`],
    title: `Une fois mais pas plus`,
    subTitle: `Ne consomme pas d'aliments trop sucrés plus d'une fois par jour`,
    description: `Les méfaits de l'excès de mauvais sucre ne sont plus à démontrer. Ta volonté à y résister, par contre, reste à démontrer.`,
    autoCompletion: false,
    duration: 7,
    level: 3,
    rules: [
      `Les interdits de la semaine sont : desserts, gâteaux, pâtisseries, bonbons, sodas, pâtes à tartiner, confitures`,
      `Un jour par semaine, tu peux consommer ce que tu veux. Ce jour peut varier de semaine en semaine, tu n'es pas obligé de le choisir à l'avance.`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Une fois mais pas plus`,
    notificationAfterCompletion: ``,
    notificationEvening: `Ouch, pas un facile celui la, mais pas le moins important, profite bien de ton ""cheap meal"".`,
  },
  {
    topics: [`Ouverture d'esprit`, ``, ``],
    title: `Mais quel est cet endroit ?`,
    subTitle: `Ne prends pas la même route que d'habitude pour aller au travail.`,
    description: `Les habitudes ont du bon, mais il faut savoir sortir de sa zone de confort. Changer ses habitudes par de petites actions peut apporter beaucoup de bien. Apres tout, comment savoir que l'on fait bien si on essaye pas tout...`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Ne prends pas le chemin que tu as l'habitude de prendre pour aller/rentrer du travail, change ne seraitce qu'une rue.`,
      `Lève les yeux, regarde autour de toi, sois le touriste de ta propre ville.`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Mais quel est cet endroit ?`,
    notificationAfterCompletion: ``,
    notificationEvening: `Oh un café ici, ""un vieux libraire ?"" ""UN MAGASIN DE CHURROS :0"" sont le genre de phrase que tu vas dire ! Génial non ?`,
  },
  {
    topics: [`Ouverture d'esprit`, ``, ``],
    title: `Mais quel est cet endroit ?`,
    subTitle: `Ne prends pas la même route que d'habitude pour aller au travail.`,
    description: `Les habitudes ont du bon, mais il faut savoir sortir de sa zone de confort. Changer ses habitudes par de petites actions peut apporter beaucoup de bien. Apres tout, comment savoir que l'on fait bien si on essaye pas tout...`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Ne Pas prendre le chemin habituel pour aller travail.`,
      `Un virage suffit`,
      `Ne pas etre distrait et observer son environnement`,
    ],
    coachAfterSummit: `C'est tres bien ca :Mais quel est cet endroit ?`,
    notificationAfterCompletion: ``,
    notificationEvening: `Oh un café ici, ""un vieux libraire ?"" ""UN MAGASIN DE CHURROS :0"" sont le genre de phrase que tu vas dire ! Génial non ?`,
  },
  {
    topics: [`Social`, `Famille/ami`, ``],
    title: `Relation epistolaire`,
    subTitle: `Ecrire à quelqu'un de ta famille ou un de tes amis.`,
    description: `A l'époque des SMS et autres applis de message, recevoir une lettre ne sers plus a rien. Sauf le bonheur immense de la recevoir. C'est un des meilleur geste a faire sans raison.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Achètes une lettre et un timbre (ou plusieurs)`,
      `Penses a quelqu'un a qui tu devrais faire plus attention`,
      `Ecris un petit mot sympathique et envoie le par la poste.`,
    ],
    coachAfterSummit: `C'est tres bien ca :Relation epistolaire`,
    notificationAfterCompletion: ``,
    notificationEvening: `Ca c'est gentil, trop peu de gens le font maintenant mais il n'y a rien de tel que de recevoir autre chose que des factures. ;)`,
  },
  {
    topics: [`Productivité`, `Technologie`, `Zen`],
    title: `Game Over`,
    subTitle: `Arretes les jeux videos pour un temps.`,
    description: `Les jeux vidéos sont parfait pour se détendre, mais ca peut des fois être dur de arrêter, Pourtant c'est extrêmement chronophage, on ne peut que s'en rendre compte lorsqu'un fait une pause. Allez c'est le moment.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Arrêtes les jeux vidéos pendant toute la durée du challenge
(ca inclut : jeux de portables, jeux d'ordinateur, consoles et console portable)`,
      ``,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Game Over`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Apprentissage`, `Alimentation`],
    title: `C'est un délice`,
    subTitle: `Essayer une nouvelle recette`,
    description: `C'est tres agréable de cuisiner mais il est prouvé que beaucoup de gens cuisinent souvent deux a trois plats en boucle. C'est le moment de tester quelque chose de neuf. Au fourneaux.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Trouver une novuelle recette, sur itnernet ou aupres d'un proche.`,
      `se procurer tout le necessaire`,
      ` Déguster et apprendre !`,
    ],
    coachAfterSummit: `C'est tres bien ca :C'est un délice`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Décroche`,
    subTitle: `Se passer de son portable`,
    description: `Le portable, bien que pratique, hypnotise et est extremement chronophage. S'en passer peut aider a une prise de conscience du besoin de réduire le temps passé dessus.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas allumer son portable, sauf appel entrant pendant le durée du challenges.`,
      `Autorisation de l'allumer pour les besoins types professionnels`,
      `Autorisation de l'allumer pour les besoins urgent`,
    ],
    coachAfterSummit: `C'est tres bien ca :Décroche`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Mode Avion`,
    subTitle: `Se passer d'internet`,
    description: `Internet est devenu la clé de voute du monde moderne, on l'utilise constamment certaines fois sans meme s'en rendre compte. Passer un moment sans utiliser le moindre service connecté, c'est s'autoriser d'ouvrir les yeux.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      ` Ne pas utiliser internet durant la durée du Challenge.`,
      `Autorisation de l'utiliser si ce n'est pas contournable`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Mode Avion`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Apprentissage`, `Productivité`, `Zen`],
    title: `La Bibilioteque ?`,
    subTitle: `Aller à la Bibliotheque`,
    description: `Il est tres compliqué de s'apercevoir du ""bruit ambiant"" que peut avoir un environnement, les bibliotheques municipales mettent a disposition un havre de paix et de connaissance dans la jungle urbaine. Y pénetrer bouquiner ou travailler, c'est avant tout : se reposer.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Prendre de quoi travailler ou lire, ou rien !`,
      `Aller a une biblioteque public`,
      `y rester le temps demandé par le challenge`,
    ],
    coachAfterSummit: `C'est tres bien ca :La Bibilioteque ?`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Débrouillard`, `Technologie`, ``],
    title: `Zero de tension`,
    subTitle: `Se passer d'electricité`,
    description: `L'electricité est partout, il y a de grandes chances qu'en levant le coude vous activiez un capteur non loin de vous, se passer d'electricité c'est tout simplement revenir a lage de Pierre. La simplicité c'est benefique`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas utiliser l'electricité (sous toute ses formes)`,
      `Autorisation de l'utiliser pour cas non contournables (exemple interphone)`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Zero de tension`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Binge-Calmer`,
    subTitle: `Se passer de Streaming (Netflix, Amazon prime …)`,
    description: `Le portable, bien que pratique, hypnotise et est extremement chronophage. S'en passer peut aider a une prise de conscience du besoin de réduire le temps passé dessus.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas regarder de série, film sur un service de streaming.`,
      `Autorisation a aller au cinéma ou de regarder a télé traditionelle (non sur demande)`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Binge-Calmer`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Binge-Calmer`,
    subTitle: `Se passer de Streaming (Netflix, Amazon prime …)`,
    description: `Le portable, bien que pratique, hypnotise et est extremement chronophage. S'en passer peut aider a une prise de conscience du besoin de réduire le temps passé dessus.`,
    autoCompletion: false,
    duration: 3,
    level: 2,
    rules: [
      `Ne pas regarder de série, film sur un service de streaming.`,
      `Autorisation a aller au cinéma ou de regarder a télé traditionelle (non sur demande)`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Binge-Calmer`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Sans réseau`,
    subTitle: `Se passer de réseau social`,
    description: `Les réseaux sociaux, c'est immense, c'est trop grand. Combien de temps est perdu tous les jours sur ces sites, il est temps de se mettre en mode avion.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas ouvrir de réseau social`,
      `Aucune notification ne doit etre lue`,
      `Autorisation d'utilisation pour des cas urgents (professionnel ou personnel)`,
    ],
    coachAfterSummit: `C'est tres bien ca :Sans réseau`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Technologie`, `Addiction`, `Zen`],
    title: `Faire écran`,
    subTitle: `Se passer de télévision`,
    description: `La télévision peut faire penser a un miroir sombre ou se jetter culture et amusement, le seul probleme et que ca represente surtout une activité ou nous restons passifs.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas alllumer sa television durant toute la durée de l'épreuve`,
      ``,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Faire écran`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Créativité`, `Productivité`, ``],
    title: `C'est joli ca !`,
    subTitle: `Dessine et crée`,
    description: `Donne toi du temps, a toi, libère ton âme d’artiste en te donnant une heure minimum pour dessiner ou peindre.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      ` Mets toi dans un environnement studieux, sans ecran, sans distraction.`,
      `Laisse sortir l’artiste qui est en toi, ca fait du bien de dessiner un peu !`,
      ` Donne toi au minimum une heure et laisse toi aller, crée !`,
    ],
    coachAfterSummit: `C'est tres bien ca :C'est joli ca !`,
    notificationAfterCompletion: `Les pratiques tels que le dessin demande de l’entraiment pour s’améliorer, c'est super.`,
    notificationEvening: `Ressource toi cette nuit, et demain, tu mets tous ces beaux rêves sur papier.`,
  },
  {
    topics: [`Créativité`, `Productivité`, ``],
    title: `Raconte moi`,
    subTitle: `Ecris sur ta journée`,
    description: `Le pouvoir de délivrance par l'écriture est incroyable, Il faut s'accrocher quand on commencer mais ca en vaut la peine,`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      ` Mets toi dans un environnement studieux, sans ecran, sans distraction.`,
      `Ecris au moins un paragraphe sur ta journée`,
      `Ne cherche pas compliquer la tache, libere toi.`,
    ],
    coachAfterSummit: `C'est tres bien ca :Raconte moi`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Vie en société`, `Ouverture d'esprit`, `Social`],
    title: `Ma ville`,
    subTitle: `Participer a sa ville`,
    description: `Nous sommes tous citoyen, s'imliquer dans la vie de son quartier ou de sa mairie est excellent pour comprendre le sens de ce mot. Beaucoup d'activités sont proposées par les mairies.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Renseigne toi sur le site internet de ta mairie ou directemenr sur place`,
      `Selectionne un moyen de participer activement a ta ville`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Ma ville`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Aujourd'hui je ..`,
    subTitle: `Ne pas procrastiner`,
    description: `Procrastiner est une véritable maladie, savoir ne pas se déroger a ses obligations est extremement bénéfique. Une tache reportée est une tache qui allourdit sa conscience.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Interdiction de procrastiner durant toute la duree du challenger`,
      `Effectuer tout de suite tout ce qui peut etre effectué tout de suite`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Aujourd'hui je ..`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Social`, `Famille/ami`, ``],
    title: `Allo ?`,
    subTitle: `Appel XXX et prends des nouvelles`,
    description: `Recevoir un coup de fil amical sans but est une source de bonheur immense, prendre des nouvelles d'un proche est une action tres accessible a notre époque.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Profiter d'un temps mort et s'emparer de son telephone`,
      `Appeler un proche sans raison`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Allo ?`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Social`, `Famille/ami`, ``],
    title: `La famille !`,
    subTitle: `Appel un membre de ta famille`,
    description: `Il n'est jamais assez répété que la famille est unique, il faut savoir etre la pour ses proches quels que soient les différents. Il faut tres peu d'effort et de temps pour cet acte si fort de sens`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [
      `Profiter d'un temps mort et s'emparer de son telephone`,
      `Appeler un membre de ta famille sans raison`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :La famille !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Santé`, `Addiction`, `Economie`],
    title: `Le tabac c'est tabou`,
    subTitle: `Se passer de cigarettes`,
    description: `Le tabac est l'une des premiere cause de mortalité au monde, il est inutile de rappeler le besoin de s'en passer.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [`Ne pas fumer`, `Ne pas posseder de cigarette sur sois`, ``],
    coachAfterSummit: `C'est tres bien ca :Le tabac c'est tabou`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Santé`, `Addiction`, `Economie`],
    title: `Dark Vapote`,
    subTitle: `Se passer de l'e-cigarette`,
    description: `Le vapotage est venu en force remplacer la cigarette, non comparable d'un point de vue danger, l'e cigarette reste une habitude qu'il est bon d'arreter`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [`Ne pas Vapoter`, `Ne pas avoir de E-cigarette sur sois`, ``],
    coachAfterSummit: `C'est tres bien ca :Dark Vapote`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Santé`, `Addiction`, ``],
    title: `TOC TOC TOC`,
    subTitle: `Surpasser ses Tocs`,
    description: `Beaucoup de gens ont des tocs, meme sans s'en rendre compte, l'habilité de s'auto discipliner lorsqu'une occurrence arrive est extremement encourageante.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Porter une attention particuliere a ce qui s'apparente a un TOC`,
      `Prendre conscience de chaque fois que le TOC surviens `,
      `Controler au maximum les apparations durant toute la duré de l'épreuve`,
    ],
    coachAfterSummit: `C'est tres bien ca :TOC TOC TOC`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ecologie`, `Vie en société`, `Economie`],
    title: `Multi usage`,
    subTitle: `Ne pas utiliser d'objet a usage unique`,
    description: `L'écologie, c'est l'affaire de tous, et ca passe obligatoirement par une modification de ses habitudes. Les objets a usages uniques sont presque tous remplacables par d'autres plus écologique.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Multi usage`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ecologie`, `Vie en société`, ``],
    title: `Sans plastique`,
    subTitle: `Se passer de plastique`,
    description: `L'écologie, c'est l'affaire de tous, et ca passe obligatoirement par une modification de ses habitudes. Le plastique est l'une des matieres les plus polluantes du monde, des alternatives existes, c'est le moment.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Sans plastique`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ecologie`, `Economie`, ``],
    title: `Sans soif`,
    subTitle: `Se munir d'une gourde`,
    description: `L'écologie, c'est l'affaire de tous, et ca passe obligatoirement par une modification de ses habitudes. Les objets a usages uniques sont presque tous remplacables par d'autres plus écologique.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Sans soif`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Culture générale`, `Ouverture d'esprit`, ``],
    title: `Silence, Action !`,
    subTitle: `Voir un film oscarisé`,
    description: `L'industrie du cinéma sors plus de 4000 films par an a travers le monde , parmis eux, une dizaine seulement est oscarisée. Si il faut en voir un ? Pourquoi pas un de ceux la.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Silence, Action !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Culture générale`, `Ouverture d'esprit`, `Apprentissage`],
    title: `Conférence`,
    subTitle: `Regarder un Ted Talk`,
    description: `Ted Talk est une véritable référence dans le monde de la conférence, tous les sujets peuvent y etre abordés et on ne perds rarement le temps passé.`,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Conférence`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Reveil, Debout, …`,
    subTitle: `Créer une nouvelle routine matinale`,
    description: `Avoir une routine est un rempart contre la procrastination, l'habitude prise grace a la routine demande moins d'énergie et d'attention.  `,
    autoCompletion: false,
    duration: 14,
    level: 2,
    rules: [
      `Trouve quelque chose que tu aimerais faire quotidiennement`,
      `Installe cette action comme une habitude.`,
      `ne zappes aucune itération pendant la durée du challenge`,
    ],
    coachAfterSummit: `C'est tres bien ca :Reveil, Debout, …`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Reveil, Debout, …`,
    subTitle: `Créer une nouvelle routine matinale`,
    description: `Avoir une routine est un rempart contre la procrastination, l'habitude prise grace a la routine demande moins d'énergie et d'attention.  `,
    autoCompletion: false,
    duration: 30,
    level: 3,
    rules: [
      `Trouve quelque chose que tu aimerais faire quotidiennement`,
      `Installe cette action comme une habitude.`,
      `ne zappes aucune itération pendant la durée du challenge`,
    ],
    coachAfterSummit: `C'est tres bien ca :Reveil, Debout, …`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Reveil, Debout, …`,
    subTitle: `Créer une nouvelle routine matinale`,
    description: `Avoir une routine est un rempart contre la procrastination, l'habitude prise grace a la routine demande moins d'énergie et d'attention.  `,
    autoCompletion: false,
    duration: 7,
    level: 2,
    rules: [
      `Trouve quelque chose que tu aimerais faire quotidiennement`,
      `Installe cette action comme une habitude.`,
      `ne zappes aucune itération pendant la durée du challenge`,
    ],
    coachAfterSummit: `C'est tres bien ca :Reveil, Debout, …`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Bip bip c'est l'heure de :`,
    subTitle: `Créer une nouvelle routine quotidienne`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Bip bip c'est l'heure de :`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Productivité`, ``, ``],
    title: `Au lit, mais avant c'est …`,
    subTitle: `Créer une nouvelle routine de soirée`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Au lit, mais avant c'est …`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Vie en société`, ``],
    title: `J'positivisme`,
    subTitle: `Ne pas utiliser de terme négatif`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :J'positivisme`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Vie en société`, `Zen`],
    title: `Courtoiserie`,
    subTitle: `Ne pas dire de grots mots`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Courtoiserie`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Vie en société`, `Zen`],
    title: `La bave du crapaud..`,
    subTitle: `Ne pas s'énerver`,
    description: `Personne n'a encore prouver que s'enerver mene quelque part … restes Zen et contient chaque exces de colere.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas hausser le ton`,
      `Garder son calme`,
      `Ne pas s'enerver seul ou envers quelqu'un`,
    ],
    coachAfterSummit: `C'est tres bien ca :La bave du crapaud..`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Social`, `Vie en société`, ``],
    title: `T'as de beaux yeux tu sais`,
    subTitle: `Regarder les gens dans les yeux`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :T'as de beaux yeux tu sais`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Culture générale`, `Apprentissage`, ``],
    title: `Arte Fact`,
    subTitle: `Regarder un documentaire`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Arte Fact`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Alimentation`, ``],
    title: `Vor Ni Car`,
    subTitle: `Ne pas manger de viande`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Vor Ni Car`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Alimentation`, ``],
    title: `Nos amis les betes`,
    subTitle: `Ne pas manger de produits provenant d'animaux`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Nos amis les betes`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Simplicité`, `Zen`, ``],
    title: `Trop c'est trop !`,
    subTitle: `Se débarasser de choses non utiles`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Trop c'est trop !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Simplicité`, `Zen`, ``],
    title: `Poids plume`,
    subTitle: `Voyager leger`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Poids plume`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Zen`, `Alimentation`, ``],
    title: `Zombie Off`,
    subTitle: `Ne pas manger devant des écrans`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Zombie Off`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Zen`, `Vie en société`, ``],
    title: `Raide nuque`,
    subTitle: `Ne pas utiliser son portable dans les transports`,
    description: `Le portable, est un passe temps parfait pour les transports on s'y perd pendant des heures a fixer du vide ou jouer a dex jeux pas forcement tres intelligents. Profites du temps de transport pour t'ennuyer, lire ou observer.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Ne pas sortir son portable de sa poche dans les transports`,
      `Autorisation de le sortir pour regarder sa route`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Raide nuque`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Zen`, `Vie en société`, ``],
    title: `Raide nuque`,
    subTitle: `Ne pas utiliser son portable dans les transports et dans la rue`,
    description: `Le portable, est un passe temps parfait pour les transports on s'y perd pendant des heures a fixer du vide ou jouer a dex jeux pas forcement tres intelligents. Profites du temps de transport pour t'ennuyer, lire ou observer.`,
    autoCompletion: false,
    duration: 1,
    level: 2,
    rules: [
      `Ne pas sortir son portable de sa poche dans les transports`,
      `Autorisation de le sortir pour regarder sa route`,
      `Ne pas sortir son portable dans lorsque l'on marche dans la rue`,
    ],
    coachAfterSummit: `C'est tres bien ca :Raide nuque`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Alimentation`, `Addiction`, `Santé`],
    title: `Allergique`,
    subTitle: `Ne mange pas X`,
    description: `On a tous un aliment que l'on mange trop, ca peut etre une sucrerie, un gateau ou meme du pain. Fais une pause, et apprends a l'apprécier a sa juste valeur a nouveau.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Décider d'un aliment que tu aimerais réduire un peu.`,
      `Ne pas en manger pendant toute la durée du challenge.`,
      ``,
    ],
    coachAfterSummit: `C'est tres bien ca :Allergique`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Alimentation`, `Addiction`, `Santé`],
    title: `Allergique Masochiste`,
    subTitle: `Ne mange pas X (expert)`,
    description: `On a tous un aliment que l'on mange trop, ca peut etre une sucrerie, un gateau ou meme du pain. Fais une pause, et apprends a l'apprécier a sa juste valeur a nouveau.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `Décider d'un aliment que tu aimerais réduire un peu.`,
      `Ne pas en manger pendant toute la durée du challenge.`,
      `Avoir toujours cet aliment a porter de main et de regard`,
    ],
    coachAfterSummit: `C'est tres bien ca :Allergique Masochiste`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sommeil`, `Technologie`, ``],
    title: `Debout la dedans`,
    subTitle: `Reveille toi sans reveil le matin`,
    description: `Se lever le matin doit normalement etre une tache autonome, l'être humain déclenche lui-même la fin d'un cycle de sommeil au moment oportun. `,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Debout la dedans`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sommeil`, `Santé`, ``],
    title: `Bonne nuit`,
    subTitle: `Couche toi avant 21H`,
    description: `Le temps n'étant pas extensible, il n'y a pas beaucoup de possibilités pour rallonger une nuit de sommeil, se coucher a une heure décente permet de s'endormir doucement et d'avoir un sommeil plus profond.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Bonne nuit`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Santé`, `Ouverture d'esprit`, ``],
    title: `A gla gla`,
    subTitle: `Prendre une douche froide`,
    description: `Outre l'amelioration de la ciruculation sanguine et la stimulation du système immunitaire, la douche froide repose et reveille. Il faut y aller progressivement mais ca vaut le coup.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [
      `En début de journée, le soir ou apres le sport`,
      `Prendre une douche normal ou l'on réduit la température progressivement.`,
      `Rester le plus longtemps possible sous la température la plus froide possible`,
    ],
    coachAfterSummit: `C'est tres bien ca :A gla gla`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Santé`, `Ouverture d'esprit`, ``],
    title: `A gla gla GLA`,
    subTitle: `Prendre une douche froide`,
    description: `Outre l'amelioration de la ciruculation sanguine et la stimulation du système immunitaire, la douche froide repose et reveille. Il faut y aller progressivement mais ca vaut le coup.`,
    autoCompletion: false,
    duration: 7,
    level: 2,
    rules: [
      `En début de journée, le soir ou apres le sport`,
      `Prendre une douche normal ou l'on réduit la température progressivement.`,
      `Rester le plus longtemps possible sous la température la plus froide possible`,
    ],
    coachAfterSummit: `C'est tres bien ca :A gla gla GLA`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Addiction`, ``],
    title: `Plus sot`,
    subTitle: `Se passer de sexe`,
    description: `L'attente fait monter l'envie, ne pas céder à a ses pulsions sexuelle permet de recharger sa libido et de profiter un maximum de la fois suivante.`,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [`Ne pas se toucher`, `Ne pas avoir de rapport sexuel`, ``],
    coachAfterSummit: `C'est tres bien ca :Plus sot`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `Mais qu'est c.. OH !`,
    subTitle: `ne pas faire X position`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Mais qu'est c.. OH !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `La salle X`,
    subTitle: `Ne pas le faire dans le lit`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :La salle X`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `A table ?`,
    subTitle: `Le faire avec l'utilisation d'un aliment`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :A table ?`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `Pas dedans`,
    subTitle: `Le faire sans pénétration`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Pas dedans`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `Blind test`,
    subTitle: `Le faire sans regarder`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Blind test`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Sexualité`, `Ouverture d'esprit`, ``],
    title: `50 shades`,
    subTitle: `Le faire attaché`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :50 shades`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Social`, ``],
    title: `Rooooh !`,
    subTitle: `Ne pas se plaindre`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Rooooh !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Social`, ``],
    title: `Merci !`,
    subTitle: `Dire merci`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Merci !`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Positivité`, `Zen`, ``],
    title: `+ + +`,
    subTitle: `Ecrire trois choses positives sur sa journée`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :+ + +`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Alimentation`, `Santé`, `Addiction`],
    title: `Gris gnoter`,
    subTitle: `Ne pas manger en dehors des repas`,
    description: ``,
    autoCompletion: false,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Gris gnoter`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Social`, ``],
    title: `Bar a cudda`,
    subTitle: `Aller dans un bar que l’on ne connait pas`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Bar a cudda`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Social`, ``],
    title: `Le club Secret`,
    subTitle: `Aller dans un nouveau club`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Le club Secret`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Ouverture d'esprit`, `Culture général`, `Social`],
    title: `Sur les planches`,
    subTitle: `Aller voir une piece de theatre`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Sur les planches`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Social`, `Famille/Ami`, ``],
    title: `Camera café`,
    subTitle: `Crever un abcès avec un collegue`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :Camera café`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
  {
    topics: [`Social`, `Famille/Ami`, ``],
    title: `viens la toi`,
    subTitle: `Crever un abcès avec un.e ami.e`,
    description: ``,
    autoCompletion: true,
    duration: 1,
    level: 1,
    rules: [``, ``, ``],
    coachAfterSummit: `C'est tres bien ca :viens la toi`,
    notificationAfterCompletion: ``,
    notificationEvening: ``,
  },
];

export const emptyChallenge = {
  topics: [``, ``],
  title: ``,
  subTitle: ``,
  description: ``,
  autoCompletion: false,
  duration: 0,
  level: 0,
  rules: [``, ``, ``],
  coachAfterSummit: ``,
  notificationAfterCompletion: ``,
  notificationEvening: ``,
};
